[b]Dragon Ball Kai Online[/b]

[color=red]New Server Arena!! (Server Testes!!)<br>[/color]
<br>

  [color=red]Nuevo Servidor Arena DBKO!<br>[/color]
-|Nuevos Comandos: lvl Bug, comando UnBug Level "bug", Band Of Loss "bol", "bc" !!!!
<br>
<br>
<br>
      [color=red]Que Hay De Nuevo?<br>[/color]
- [color=blue]Enchant [/color]- Enchant Item de +1 a +10, con Atributos,<br>
- [color=blue]Sistema de Party[/color] - Con Experiencia para el grupo asta en PVP.<br>
- [color=blue]Shenron[/color] + Radar - Radar Sheron 100 %!<br>
- [color=blue]Protect Level[/color] -level 50, y players ganaran exp matando otros.'<br>